# Python Scientific Computing Cheat Sheet

## NumPy arrays

NumPy arrays can be used to store multiple measurements, such as accuracy or response times from a task.

In [1]:
import numpy as np                   # the standard way to import numpy
integers = np.array([1, 2, 3])       # create an array by passing a list to np.array
floats = np.array([1.1, 2.2, 3.3])   # can also store decimals in float data type
letters = np.array(["a", "b", "c"])  # can store string data in an array
print(integers, integers.dtype)      # each array has a data type
print(floats, floats.dtype)          # decimals are stored with float data type
print(letters, letters.dtype)        # string data type indicates text format

[1 2 3] int64
[1.1 2.2 3.3] float64
['a' 'b' 'c'] <U1


Arrays may have different numbers of dimensions.

In [2]:
# create a 1D array from a list
array1d = np.array([1, 2])
print(array1d)

[1 2]


In [3]:
# create a 2D array from a list of lists
array2d = np.array([[1, 2], [3, 4]])
print(array2d)

[[1 2]
 [3 4]]


Arrays have *attributes* that tell us about their properties. Attributes can be accessed by typing the name of the variable, a dot (`.`), and then the name of the attribute (for example, `size`).

In [4]:
print(array2d.size)   # total number of items
print(array2d.ndim)   # number of dimensions
print(array2d.shape)  # size of each dimension

4
2
(2, 2)


## Array expressions

Use mathematical expressions with NumPy arrays to efficiently run calculations.

In [5]:
array1 = np.array([1, 2, 3, 4])
print(array1)
print(array1 + 3)   # add to each of the items
print(array1 - 4)   # subtract from each of the items
print(array1 * 2)   # multiply by a value
print(array1 / 2)   # divide by a value
print(array1 ** 3)  # take values to a power

[1 2 3 4]
[4 5 6 7]
[-3 -2 -1  0]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  8 27 64]


In [6]:
array2 = np.array([1, 1, 2, 2])
print(array1 + array2)   # add arrays
print(array1 - array2)   # subtract arrays
print(array1 * array2)   # multiple matching elements of arrays
print(array1 / array2)   # divide matching elements of arrays
print(array1 ** array2)  # take array1 items to the power of array2 items

[2 3 5 6]
[0 1 1 2]
[1 2 6 8]
[1.  2.  1.5 2. ]
[ 1  2  9 16]


In [7]:
print(array1 @ array2)  # calculate the dot product between arrays

17


## Array creation functions

Use array creation functions to create arrays with a range of values or all zeros or ones.

In [8]:
r1 = np.arange(1, 11)       # 1 to 11 (non inclusive), with a step of 1
r2 = np.arange(1, 11, 0.5)  # 1 to 11 (non inclusive), with a step of 0.5
print(r1)
print(r2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]


In [9]:
l1 = np.linspace(0, 8, 5)   # 5 linearly spaced values from 0 to 8
l2 = np.linspace(0, 8, 10)  # 10 linearly spaced values from 0 to 8
print(l1)
print(l2)

[0. 2. 4. 6. 8.]
[0.         0.88888889 1.77777778 2.66666667 3.55555556 4.44444444
 5.33333333 6.22222222 7.11111111 8.        ]


In [10]:
z1 = np.zeros(6)              # an array with all zeros
z2 = np.zeros(6, dtype=int)   # same, but use integers instead of floats
z3 = np.zeros((2, 3))         # two rows and three columns
z4 = np.zeros(4, dtype=bool)  # boolean array filled with False
print(z1)
print(z2)
print(z3)
print(z4)

[0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]
[False False False False]


In [11]:
o1 = np.ones(6)                  # an array with all ones
o2 = np.ones((2, 3), dtype=int)  # two rows and three columns of integers
o3 = np.ones(4, dtype=bool)      # boolean array filled with True
print(o1)
print(o2)
print(o3)

[1. 1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]
[ True  True  True  True]


## Array indexing

Use indexing to get data values from part of an array.

In [12]:
a = np.arange(1, 11)
print(a)
print(a[9])    # get the item at index 9, counting from zero
print(a[:5])   # get the first five items
print(a[-5:])  # get the last five items

[ 1  2  3  4  5  6  7  8  9 10]
10
[1 2 3 4 5]
[ 6  7  8  9 10]


In [13]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
print(matrix[1])     # get the second row (at index 1)
print(matrix[1, :])  # same, but explicitly indicate all columns included
print(matrix[:, 1])  # get the second column
print(matrix[1, 1])  # get the item in second row, second column


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[2 5 8]
5


In [14]:
print(matrix[:2, :2])    # get first two rows and first two columns
print(matrix[-2:, -2:])  # get last two rows and last two columns

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]
