# Assignment 5

Please fill in blanks in the *Answer* sections of this notebook. To check your answer for a problem, run the Setup, Answer, and Result sections. DO NOT MODIFY SETUP OR RESULT CELLS. See the [README](https://github.com/mortonne/datascipsych) for instructions on setting up a Python environment to run this notebook.

Write your answers for each problem. Then restart the kernel, run all cells, and then save the notebook. Upload your notebook to Canvas.

If you get stuck, read through the other notebooks in this directory, ask us for help in class, or ask other students for help in class or on the weekly discussion board.

## Problem: creating a NumPy array (2 points)
Create a NumPy array called `x` with the following data: 0.4, 0.8, 1.5, 1.6, 2.3, 4.2.

### Setup

In [74]:
import numpy as np
x = None

### Answer

In [75]:
x = np.array([0.4, 0.8, 1.5, 1.6, 2.3, 4.2])
x

array([0.4, 0.8, 1.5, 1.6, 2.3, 4.2])

### Result

In [76]:
if x is not None:
    # this should print your array
    print(x)
    
    # this should not throw any errors
    assert isinstance(x, np.ndarray)
    assert x[2] == 1.5
    assert x.size == 6
    assert x.ndim == 1
    assert x.dtype == float

[0.4 0.8 1.5 1.6 2.3 4.2]


## Problem: using array generation functions (2 points)
Create an array of 4 zeros called `x_zeros` using `np.zeros`. Create a 3 x 3 x 3 array of ones called `x_ones` using `np.ones`. Create an array called `x_range` with the numbers 3 through 6 (inclusive) using `np.arange`.

### Setup

In [89]:
x_zeros = None
x_ones = None
x_range = None

### Answer

In [90]:
# your code here
x_zeros = np.zeros(4)
display(x_zeros)
x_ones = np.ones((3, 3))
display(x_ones)
x_range = np.arange(3, 7)
display(x_range)

array([0., 0., 0., 0.])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([3, 4, 5, 6])

### Result

In [91]:
vars = [x_zeros, x_ones, x_range]
if all([v is not None for v in vars]):
    # this should print your arrays
    print(x_zeros)
    print(x_ones)
    print(x_range)
    
    # this should not throw any errors
    assert isinstance(x_zeros, np.ndarray)
    assert isinstance(x_ones, np.ndarray)
    assert isinstance(x_range, np.ndarray)
    assert np.all(x_zeros == 0)
    assert x_zeros.ndim == 1
    assert x_zeros.shape == (4,)
    assert np.all(x_ones == 1)
    assert x_ones.ndim == 3
    assert x_ones.shape == (3, 3, 3)
    assert x_range[0] == 3
    assert x_range[-1] == 6
    assert x_range.size == 4
    assert x_range.ndim == 1

[0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[3 4 5 6]


AssertionError: 

## Problem: accessing array attributes (2 points)
For the array `z` (defined below), use array attributes (accessed using `z.[attribute]`) to get the number of dimensions, the size of each dimension, and the total number of elements.

### Setup

In [39]:
z = np.array([[1, 2, 3], [4, 5, 6]])
zdims = None
zshape = None
ztot = None

### Answer

In [97]:
# your code here
print(f"Number of dimensions: {z.ndim}")
print(f"Size of each dimension: {z.shape}")
print(f"Total number of elements: {z.size}")

Number of dimensions: 2
Size of each dimension: (2, 3)
Total number of elements: 6


### Result

In [98]:

vars = [zdims, zshape, ztot]
if all([v is not None for v in vars]):
    # this should print your variables
    print(zdims, zshape, ztot)

    # this should not throw any errors
    assert zdims == 2
    assert zshape == (2, 3)
    assert ztot == 6

## Problem: accessing array data (2 points)
For the array `a` (defined below), use indexing to get the fourth item. Then use slicing to get a view of the array showing items two through four (inclusive).

### Setup

In [104]:
a = np.array([5, 4, 3, 2, 1])
a_four = None
a_two_thru_four = None

### Answer

In [107]:
# your code here
a_four = print(a[3])
a_two_thru_four = print(a[1:4])

2
[4 3 2]


### Result

In [108]:
if a_four is not None and a_two_thru_four is not None:
    # this should print your variables
    print(a_four, a_two_thru_four)

    # this should not throw any errors
    assert isinstance(a_four, np.int64)
    assert isinstance(a_two_thru_four, np.ndarray)
    assert a_four == 2
    assert np.array_equal(a_two_thru_four, np.array([4, 3, 2]))

## Problem: using array functions (2 points)
For the array `correct` (defined below), which labels a series of trials in a memory experiment by whether they were correct (1) or incorrect (0), use NumPy attributes and functions to calculate the number of trials, the total number of correct responses, and the fraction of correct responses.

### Setup

In [126]:
correct = np.array([0, 1, 1, 1, 0, 0, 1, 0, 0, 1])
n_trial = None#legnth of triqls
n_correct = None #correct
fraction_correct = None #numver of correct trials/number of trials

### Answer

In [127]:
# your code here
(f"Toal size of array: {correct.size}")
n_trial = correct.size
print(f"Total number of trials: {n_trial}")
n_correct = np.sum(correct)
print(f"Total correct: {n_correct}")
fraction_correct = np.mean(correct)
print(f"Fraction correct: {round(np.mean(correct)*100)}%")

Total number of trials: 10
Total correct: 5
Fraction correct: 50%


### Result

In [128]:
vars = [n_trial, n_correct, fraction_correct]
if all([v is not None for v in vars]):
    # this should print your variables
    print(n_trial, n_correct, fraction_correct)

    # this should not throw any errors
    assert n_trial == 10
    assert n_correct == 5
    assert fraction_correct == 0.5

10 5 0.5


## Problem: filtering an array (2 points)
Create a NumPy array called `b` with the following data: 12, 4, 3, 10, 15, 1. Then use array filtering with comparison operators (for example, `<`, `>`, `==`, `<=`, `>=`) to filter `b` and get an array called `c`, which has just the numbers that are less than or equal to 10.

### Setup

In [48]:
b = None
c = None

### Answer

In [49]:
# your code here

### Result

In [50]:
if b is not None and c is not None:
    # this should print your arrays
    print(b, c)
    
    # this should not throw any errors
    assert isinstance(b, np.ndarray)
    assert isinstance(c, np.ndarray)
    assert b[2] == 3
    assert b.size == 6
    assert np.array_equal(c, np.array([4, 3, 10, 1]))

## Problem (graduate students): data analysis using NumPy (4 points)
Say that you have data from a psychology experiment where participants had to make responses in two conditions: A and B. For each trial, you have a variable indicating whether the response was correct and a variable indicating the response time. The table below shows the data for six trials.

| condition | correct | response_time |
| --------- | ------- | ------------- |
| A         | 1       | 1.5           |
| B         | 1       | 1.3           |
| A         | 0       | 2.9           |
| B         | 1       | 1.2           |
| B         | 1       | 1.4           |
| A         | 0       | 2.3           |

Create NumPy arrays called `condition`, `correct`, and `response_time` to represent each variable in the study. Then use array filtering (see the Filtering arrays section in the lecture) and NumPy functions (see the Array functions section in the lecture) to calculate fraction correct in condition A, fraction correct in condition B, mean response time in condition A, and mean response time in condition B.

### Setup

In [51]:
condition = None
correct = None
response_time = None
accuracy_A = None
accuracy_B = None
response_time_A = None
response_time_B = None

### Answer

In [52]:
# your code here

### Result

In [53]:
vars = [condition, correct, response_time, accuracy_A, accuracy_B, response_time_A, response_time_B]
if all([x is not None for x in vars]):
    # this should print your arrays
    print(condition)
    print(correct)
    print(response_time)
    print(f"{accuracy_A=}, {accuracy_B=}, {response_time_A=}, {response_time_B=}")
    
    # this should not throw any errors
    assert isinstance(condition, np.ndarray)
    assert isinstance(correct, np.ndarray)
    assert isinstance(response_time, np.ndarray)
    assert round(accuracy_A, 2) == 0.33
    assert round(accuracy_B, 2) == 1.00
    assert round(response_time_A, 2) == 2.23
    assert round(response_time_B, 2) == 1.30

## Problem (graduate students): using broadcasting (4 points)
Read about [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) of NumPy arrays.

Say that you have a matrix:

$$
M = \begin{pmatrix}
    1.0 & 2.0 & 3.0 \\
    1.1 & 2.2 & 3.3 \\
    1.2 & 2.4 & 3.6 \\
    \end{pmatrix}
$$

And a set of values that you want to use to scale the columns of the matrix:

$$
S = \begin{pmatrix}
    1 & 2 & 3 \\
    \end{pmatrix}
$$

Create a 2D NumPy array called `M` with the same data as above, and a 1D NumPy array called `S`. Multiply `M` by `S` to scale each column, resulting in a new variable `M_scaled`. That is, column 1 in M should be multiplied by 1, column 2 should be multiplied by 2, and column 3 should be multiplied by 3. This will involve using the regular multiplication operator (`*`), not matrix multiplication (`@`).

### Setup

In [54]:
M = None
S = None
M_scaled = None

### Answer

In [55]:
# your code here

### Result

In [56]:
vars = [M, S, M_scaled]
if all([x is not None for x in vars]):
    # this should print your arrays
    print(M)
    print(S)
    print(M_scaled)
    
    # this should not throw any errors
    answer = np.array([[1.0, 4.0, 9.0], [1.1, 4.4, 9.9], [1.2, 4.8, 10.8]])
    assert isinstance(M, np.ndarray)
    assert isinstance(S, np.ndarray)
    assert isinstance(M_scaled, np.ndarray)
    np.testing.assert_allclose(M_scaled, answer)